import Link from "next/link";
import { notFound } from "next/navigation";
import { customerName, getCustomer } from "@/lib/customers/persistence";
import { requireTenant } from "@/lib/tenant/require-tenant";

export default async function CustomerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const context = await requireTenant(); const { id } = await params; const customer = await getCustomer(context.businessId, id); if (!customer) notFound();
  return <main className="p-8"><div className="mx-auto max-w-7xl"><Link href="/customers" className="text-sm font-medium text-gray-500">← Customers</Link><div className="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-xs text-gray-400">{customer.customerNumber}</p><h1 className="mt-1 text-3xl font-bold">{customerName(customer)}</h1><p className="mt-2 text-gray-500">{customer.phone || "No phone"} · {customer.email || "No email"}</p></div><div className="flex flex-wrap gap-3">
<Link href={`/customers/${customer.id}/account`} className="rounded-lg border border-gray-300 bg-white px-4 py-2.5 font-semibold text-gray-800 shadow-sm">Account</Link>
<Link href={`/customers/${customer.id}/sites/new`} className="rounded-lg bg-blue-600 px-4 py-2.5 font-semibold text-white">+ Add Site</Link>
</div></div>
  <div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_1fr]"><section className="rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">Sites</h2><span className="text-sm text-gray-500">{customer._count.sites}</span></div>{customer.sites.length === 0 ? <div className="p-8 text-sm text-gray-500">No sites yet. Add the first service location.</div> : customer.sites.map(site => <div key={site.id} className="border-b p-5 last:border-b-0"><p className="font-semibold">{site.name}</p><p className="mt-1 text-sm text-gray-600">{[site.address, site.city, site.state, site.postalCode].filter(Boolean).join(", ") || "No address"}</p>{site.contactName && <p className="mt-2 text-sm text-gray-500">Contact: {site.contactName}{site.contactPhone ? ` · ${site.contactPhone}` : ""}</p>}</div>)}</section><section className="rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><h2 className="font-semibold">Recent Jobs</h2><span className="text-sm text-gray-500">{customer._count.jobs}</span></div>{customer.jobs.length === 0 ? <div className="p-8 text-sm text-gray-500">No jobs yet. Jobs will appear here once the Jobs module is connected.</div> : customer.jobs.map(job => <div key={job.id} className="border-b p-5 last:border-b-0"><p className="font-semibold">{job.jobNumber}</p><p className="mt-1 text-sm text-gray-500">{job.status}</p></div>)}</section></div></div></main>;
}
