import { db } from "@/lib/db/prisma";
import { contractSchema, type ContractInput } from "@/lib/validation/contract";
import { ContractBillingCycle, ContractStatus } from "@/generated/prisma/client";

function toDate(value?: string) { return value ? new Date(value) : null; }
function contractName(customer: { firstName: string | null; lastName: string | null; companyName: string | null }) { return customer.companyName?.trim() || [customer.firstName, customer.lastName].filter(Boolean).join(" ").trim() || "Unnamed customer"; }
async function nextContractNumber(businessId: string) {
  const count = await db.contract.count({ where: { businessId } }); let number = `CON-${String(count + 1).padStart(5, "0")}`; let suffix = 1;
  while (await db.contract.findUnique({ where: { businessId_contractNumber: { businessId, contractNumber: number } } })) number = `CON-${String(count + 1).padStart(5, "0")}-${suffix++}`;
  return number;
}
export async function listContracts(businessId: string, search?: string, status?: ContractStatus) {
  const q=search?.trim(); const rows=await db.contract.findMany({ where:{businessId,archivedAt:null,...(status?{status}:{}),...(q?{OR:[{contractNumber:{contains:q,mode:"insensitive"}},{title:{contains:q,mode:"insensitive"}},{customer:{companyName:{contains:q,mode:"insensitive"}}},{customer:{firstName:{contains:q,mode:"insensitive"}}},{customer:{lastName:{contains:q,mode:"insensitive"}}}]}:{})}, select:{id:true,contractNumber:true,title:true,status:true,billingCycle:true,contractValue:true,startDate:true,endDate:true,renewalDate:true,autoRenew:true,customer:{select:{id:true,firstName:true,lastName:true,companyName:true}},site:{select:{id:true,name:true}},service:{select:{id:true,name:true}}}, orderBy:[{status:"asc"},{endDate:"asc"},{createdAt:"desc"}] });
  return rows.map(row=>({...row,contractValue:row.contractValue==null?null:Number(row.contractValue),startDate:row.startDate.toISOString(),endDate:row.endDate?.toISOString()??null,renewalDate:row.renewalDate?.toISOString()??null,customerName:contractName(row.customer)}));
}
export async function getContractFormData(businessId:string, customerId?:string){const [customers,services,sites]=await Promise.all([db.customer.findMany({where:{businessId,archivedAt:null,isActive:true},orderBy:[{companyName:"asc"},{firstName:"asc"}],select:{id:true,firstName:true,lastName:true,companyName:true}}),db.service.findMany({where:{businessId,archivedAt:null,status:"ACTIVE"},orderBy:{name:"asc"},select:{id:true,name:true}}),db.site.findMany({where:{businessId,archivedAt:null,isActive:true,...(customerId?{customerId}:{})},orderBy:{name:"asc"},select:{id:true,customerId:true,name:true}})]);return{customers,services,sites};}
export async function getContract(businessId:string,id:string){const row=await db.contract.findFirst({where:{id,businessId,archivedAt:null},select:{id:true,contractNumber:true,customerId:true,siteId:true,serviceId:true,title:true,status:true,billingCycle:true,contractValue:true,startDate:true,endDate:true,renewalDate:true,autoRenew:true,notes:true}});if(!row)return null;return{...row,contractValue:row.contractValue==null?null:Number(row.contractValue),startDate:row.startDate.toISOString().slice(0,10),endDate:row.endDate?.toISOString().slice(0,10)??"",renewalDate:row.renewalDate?.toISOString().slice(0,10)??""};}
async function validateRefs(businessId:string,input:ContractInput){const customer=await db.customer.findFirst({where:{id:input.customerId,businessId,archivedAt:null,isActive:true},select:{id:true}});if(!customer)throw new Error("Customer does not belong to this business.");if(input.siteId){const site=await db.site.findFirst({where:{id:input.siteId,businessId,customerId:input.customerId,archivedAt:null,isActive:true},select:{id:true}});if(!site)throw new Error("Selected site does not belong to the customer.");}if(input.serviceId){const service=await db.service.findFirst({where:{id:input.serviceId,businessId,archivedAt:null,status:"ACTIVE"},select:{id:true}});if(!service)throw new Error("Selected service does not belong to this business.");}}
function contractData(input:ContractInput){return{customerId:input.customerId,siteId:input.siteId||null,serviceId:input.serviceId||null,title:input.title.trim(),status:input.status as ContractStatus,billingCycle:input.billingCycle as ContractBillingCycle,contractValue:input.contractValue??null,startDate:new Date(input.startDate),endDate:toDate(input.endDate),renewalDate:toDate(input.renewalDate),autoRenew:input.autoRenew,notes:input.notes?.trim()||null};}
export async function createContract(businessId:string,input:ContractInput){const data=contractSchema.parse(input);await validateRefs(businessId,data);return db.contract.create({data:{businessId,contractNumber:await nextContractNumber(businessId),...contractData(data)}});}
export async function updateContract(businessId:string,id:string,input:ContractInput){const data=contractSchema.parse(input);await validateRefs(businessId,data);const existing=await db.contract.findFirst({where:{id,businessId,archivedAt:null},select:{id:true}});if(!existing)throw new Error("Contract not found.");return db.contract.update({where:{id},data:contractData(data)});}
export async function archiveContract(businessId:string,id:string){const existing=await db.contract.findFirst({where:{id,businessId,archivedAt:null},select:{id:true}});if(!existing)throw new Error("Contract not found.");return db.contract.update({where:{id},data:{archivedAt:new Date(),status:"CANCELLED"}});}
export async function updateContractStatus(businessId:string,id:string,status:ContractStatus){const existing=await db.contract.findFirst({where:{id,businessId,archivedAt:null},select:{id:true}});if(!existing)throw new Error("Contract not found.");return db.contract.update({where:{id},data:{status}});}
